# Generated by Django 5.0.6 on 2024-07-21 08:32

from django.db import migrations, models


def set_default_image_url(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        if not post.image:
            post.image = "http://placehold.it/900x300"
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_image_url),
    ]
